# Generated by Django 3.1.2 on 2020-10-15 16:43

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_wp_id'),
        ('posts', '0005_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='use cmd/ctrl click to select multiple categories', related_name='categories', to='categories.Category'),
        ),
    ]
