# Generated by Django 3.1.2 on 2020-11-17 17:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_region_setting'),
        ('wagtailcore', '0052_pagelogentry'),
        ('atlascasestudies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasCaseStudy',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('wp_id', models.PositiveSmallIntegerField(null=True)),
                ('wp_slug', models.TextField(blank=True, null=True)),
                ('wp_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AtlasCaseStudyIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AtlasCaseStudySettingRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atlas_case_study', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='atlas_case_study_setting_relationship', to='atlascasestudies.atlascasestudy')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='categories.setting')),
            ],
        ),
        migrations.DeleteModel(
            name='AtlasCaseSudy',
        ),
    ]
