# Generated by Django 3.1.2 on 2020-11-17 17:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_region_setting'),
        ('atlascasestudies', '0002_auto_20201117_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasCaseStudyRegionRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atlas_case_study', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='atlas_case_study_region_relationship', to='atlascasestudies.atlascasestudy')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='categories.region')),
            ],
        ),
    ]
