# Generated by Django 3.1.2 on 2020-11-17 18:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_region_setting'),
        ('atlascasestudies', '0003_atlascasestudyregionrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasCaseStudyCategoryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atlas_case_study', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='atlas_case_study_category_relationship', to='atlascasestudies.atlascasestudy')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='categories.category')),
            ],
        ),
    ]
