# Generated by Django 3.1.3 on 2020-11-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlascasestudies', '0004_atlascasestudycategoryrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlascasestudy',
            name='wp_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
