# Generated by Django 3.1.2 on 2020-10-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20201028_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsite',
            new_name='CategorySubSite',
        ),
    ]
