# Generated by Django 3.1.2 on 2020-11-16 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20201028_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationTypeSubSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('wp_id', models.PositiveSmallIntegerField(null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('sub_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.publicationtypesubsite')),
            ],
            options={
                'verbose_name': 'Publication Type',
                'verbose_name_plural': 'Publication Types',
                'ordering': ['name'],
            },
        ),
    ]
