# Generated by Django 3.1.3 on 2020-11-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_region_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
