# Generated by Django 3.1.3 on 2020-11-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_auto_20201130_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='wp_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='publicationtype',
            name='wp_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='wp_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='wp_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
