# Generated by Django 3.1.4 on 2020-12-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201126_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='footer_extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='header_extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
