# Generated by Django 3.1.3 on 2020-11-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20201117_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='wp_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
