# Generated by Django 3.1.2 on 2020-11-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationindexpage',
            options={'verbose_name': 'Publications Index Page', 'verbose_name_plural': 'Publications Index Pages'},
        ),
    ]
