# Generated by Django 3.1.2 on 2020-11-16 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20201116_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationpublicationtyperelationship',
            old_name='category',
            new_name='publication_type',
        ),
    ]
