# Generated by Django 3.1.2 on 2020-11-17 09:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_publicationtype_publicationtypesubsite'),
        ('publications', '0003_auto_20201116_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationCategoryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='categories.category')),
                ('publication', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_category_relationship', to='publications.publication')),
            ],
        ),
    ]
