# Generated by Django 3.1.2 on 2020-11-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publicationcategoryrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='wp_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='wp_slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
