# Generated by Django 3.1.2 on 2020-11-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20201117_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='date',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='modified',
        ),
    ]
