# Generated by Django 3.1.2 on 2020-11-26 15:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20201117_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='documents',
            field=wagtail.core.fields.StreamField([('document', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock())], group='Custom'))], blank=True),
        ),
    ]
