# Generated by Django 3.1.2 on 2020-11-26 16:05

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_publication_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='documents',
            field=wagtail.core.fields.StreamField([('document', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('type', wagtail.core.blocks.ChoiceBlock(choices=[('pdf', 'PDF'), ('file', 'File'), ('pdf', 'Doc'), ('xlsx', 'Excell')])), ('num_pages', wagtail.core.blocks.IntegerBlock(required=False)), ('file_size', wagtail.core.blocks.DecimalBlock(required=False))], group='Custom'))], blank=True),
        ),
    ]
