# Generated by Django 3.1.2 on 2020-11-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20201126_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='component_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
