# Generated by Django 3.1.3 on 2020-11-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_auto_20201129_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='wp_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
