#!/bin/bash
set -e

#if [ $# -eq 0 ]; then
#  echo "Linting code..."
#  script/poetry run black .
#fi

echo "Running tests..."
docker-compose run --service-ports --rm web bash -c "cd fixtures && ./copy_media.sh && cd .. && python manage.py test cms"
