# Generated by Django 3.1.2 on 2020-10-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='parent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
