# Generated by Django 3.1.2 on 2020-10-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201018_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppage',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
