# Generated by Django 3.1.2 on 2020-10-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_basepage_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='template',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
