# Generated by Django 3.1.2 on 2020-10-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_toppage_real_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='real_parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
