# Generated by Django 3.1.2 on 2020-10-23 12:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('pages', '0012_basepage_real_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopPage',
            new_name='ComponentsPage',
        ),
    ]
