# Generated by Django 3.1.2 on 2020-10-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20201023_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentspage',
            name='wp_slug',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='componentspage',
            name='wp_template',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
