# Generated by Django 3.1.2 on 2020-10-23 12:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('pages', '0014_auto_20201023_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('excerpt', models.TextField(blank=True)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('wp_id', models.IntegerField(null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('wp_template', models.CharField(blank=True, max_length=100, null=True)),
                ('wp_slug', models.TextField(null=True)),
                ('real_parent', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
