# Generated by Django 3.1.2 on 2020-10-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_landingpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentspage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='componentspage',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='componentspage',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='componentspage',
            name='real_parent',
        ),
        migrations.RemoveField(
            model_name='componentspage',
            name='source',
        ),
        migrations.RemoveField(
            model_name='componentspage',
            name='wp_id',
        ),
        migrations.RemoveField(
            model_name='componentspage',
            name='wp_slug',
        ),
        migrations.RemoveField(
            model_name='componentspage',
            name='wp_template',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='real_parent',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='source',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='wp_id',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='wp_slug',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='wp_template',
        ),
    ]
