# Generated by Django 3.1.2 on 2020-10-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_holdingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='wp_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
