# Generated by Django 3.1.2 on 2020-11-18 21:21

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtailnhsukfrontend.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_basepage_wp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='md_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='basepage',
            name='md_gateway_ref',
            field=models.TextField(blank=True, verbose_name='Gateway Ref'),
        ),
        migrations.AddField(
            model_name='basepage',
            name='md_owner',
            field=models.TextField(blank=True, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='basepage',
            name='md_pcc_reference',
            field=models.TextField(blank=True, verbose_name='PCC Reference'),
        ),
        migrations.AddField(
            model_name='basepage',
            name='raw_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basepage',
            name='body',
            field=wagtail.core.fields.StreamField([('expander_group', wagtail.core.blocks.StructBlock([('expanders', wagtail.core.blocks.ListBlock(wagtailnhsukfrontend.blocks.ExpanderBlock))]))], blank=True),
        ),
    ]
