# Generated by Django 3.1.3 on 2020-11-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0003_demopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='demopage',
            name='hero_heading',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='demopage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='demopage',
            name='hero_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='demopage',
            name='last_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demopage',
            name='next_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
