# Generated by Django 3.1.2 on 2020-11-25 12:47

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201125_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='all_publications_sub_title',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='all_publications_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
