# Generated by Django 3.1.4 on 2020-12-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_demopage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='all_news_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='all_news_sub_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='all_news_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='all_publications_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='all_publications_sub_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='all_publications_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body_image',
        ),
    ]
